-- Formação CAJU - Grão de Trigo — banco Supabase
-- Cole este arquivo inteiro no SQL Editor do Supabase e clique em Run.
-- Ele cria somente dados privados de alunos: perfil, progresso, notas e sugestões.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Aluno',
  role text not null default 'aluno' check (role in ('aluno', 'formador', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lesson_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_number text not null,
  percent numeric(5,2) not null default 0 check (percent >= 0 and percent <= 100),
  section_id text,
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, lesson_number)
);

create table if not exists public.lesson_notes (
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_number text not null,
  section_id text not null default '',
  note_type text not null check (note_type in ('section', 'reflexao', 'duvidas')),
  content text not null default '',
  updated_at timestamptz not null default now(),
  primary key (user_id, lesson_number, note_type, section_id)
);

create table if not exists public.lesson_suggestions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_number text not null,
  content text not null check (char_length(content) between 3 and 5000),
  status text not null default 'nova' check (status in ('nova', 'em_analise', 'respondida', 'arquivada')),
  created_at timestamptz not null default now()
);

-- Segurança por linha: cada aluno só acessa os próprios dados.
alter table public.profiles enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.lesson_notes enable row level security;
alter table public.lesson_suggestions enable row level security;

-- Remove políticas antigas com estes nomes, caso você rode o arquivo novamente.
drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "progress_select_own" on public.lesson_progress;
drop policy if exists "progress_insert_own" on public.lesson_progress;
drop policy if exists "progress_update_own" on public.lesson_progress;
drop policy if exists "progress_delete_own" on public.lesson_progress;
drop policy if exists "notes_select_own" on public.lesson_notes;
drop policy if exists "notes_insert_own" on public.lesson_notes;
drop policy if exists "notes_update_own" on public.lesson_notes;
drop policy if exists "notes_delete_own" on public.lesson_notes;
drop policy if exists "suggestions_select_own" on public.lesson_suggestions;
drop policy if exists "suggestions_insert_own" on public.lesson_suggestions;

create policy "profiles_select_own"
on public.profiles for select to authenticated
using ((select auth.uid()) = id);

create policy "profiles_insert_own"
on public.profiles for insert to authenticated
with check ((select auth.uid()) = id);

create policy "profiles_update_own"
on public.profiles for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "progress_select_own"
on public.lesson_progress for select to authenticated
using ((select auth.uid()) = user_id);

create policy "progress_insert_own"
on public.lesson_progress for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "progress_update_own"
on public.lesson_progress for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "progress_delete_own"
on public.lesson_progress for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "notes_select_own"
on public.lesson_notes for select to authenticated
using ((select auth.uid()) = user_id);

create policy "notes_insert_own"
on public.lesson_notes for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "notes_update_own"
on public.lesson_notes for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "notes_delete_own"
on public.lesson_notes for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "suggestions_select_own"
on public.lesson_suggestions for select to authenticated
using ((select auth.uid()) = user_id);

create policy "suggestions_insert_own"
on public.lesson_suggestions for insert to authenticated
with check ((select auth.uid()) = user_id);

-- Privilégios mínimos para o navegador.
revoke all on public.profiles from anon;
revoke all on public.lesson_progress from anon;
revoke all on public.lesson_notes from anon;
revoke all on public.lesson_suggestions from anon;

grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.lesson_progress to authenticated;
grant select, insert, update, delete on public.lesson_notes to authenticated;
grant select, insert on public.lesson_suggestions to authenticated;
grant usage, select on sequence public.lesson_suggestions_id_seq to authenticated;

-- Cria automaticamente um perfil quando um usuário se cadastra.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email, 'Aluno'), '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
